### PR TITLE
Relicense Crossbow under dual MIT/Apache-2.0

### PR DESCRIPTION
**Pull request by enfipy**
# Objective

- Updates Licenses to `MIT` or `Apache-2.0`.

Contributor checkoff:

- [x] @enfipy
- [x] @Heezay 
- [x] @Adoka3710 
- [x] @olvyko 
- [x] @rodrigocam 
- [x] @beling

### CODE REVIEW

**Comment by Heezay** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by beling** [comment]
Great idea! Of course, I agree.

**Comment by enfipy** [comment]
@beling Thank you!

Can you paste this message into the comments?

```
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
```

**Comment by beling** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Adoka3710** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by olvyko** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by rodrigocam** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Pull request merged**
